---
name: Build and test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y gcc g++
    - name: Compile C file
      run: gcc examples/covercrypt.c -Wall -Wextra -Werror -o covercrypt_c -I include/ -L lib/ -lcloudproof
    - name: Compile C++ file
      run: g++ examples/covercrypt.cpp -Wall -Wextra -Werror -o covercrypt_cpp -I include/ -L lib/ -lcloudproof
    - name: Run C file example
      run: LD_LIBRARY_PATH=lib ./covercrypt_c
    - name: Run C++ file example
      run: LD_LIBRARY_PATH=lib ./covercrypt_cpp
